// <auto-generated />
using System;
using Calendar.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Calendar.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240715155511_addEventTable")]
    partial class addEventTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Calendar.Models.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long>("Color")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("Date")
                        .IsRequired()
                        .HasColumnType("Date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = 255L,
                            Date = new DateTime(2024, 7, 15, 23, 55, 11, 241, DateTimeKind.Local).AddTicks(6481),
                            Title = "Lunch"
                        },
                        new
                        {
                            Id = 2,
                            Color = 16711680L,
                            Date = new DateTime(2024, 7, 15, 19, 55, 11, 241, DateTimeKind.Local).AddTicks(6514),
                            Title = "Work"
                        },
                        new
                        {
                            Id = 3,
                            Color = 32768L,
                            Date = new DateTime(2024, 7, 15, 15, 55, 11, 241, DateTimeKind.Local).AddTicks(6520),
                            Title = "Start"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
