// <auto-generated />
using System;
using Calendar.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Calendar.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240715221907_addEventTable")]
    partial class addEventTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Calendar.Models.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "FF0000",
                            Date = new DateTime(2024, 7, 16, 6, 19, 6, 962, DateTimeKind.Local).AddTicks(6851),
                            Title = "Lunch"
                        },
                        new
                        {
                            Id = 2,
                            Color = "FFFF00",
                            Date = new DateTime(2024, 7, 16, 2, 19, 6, 962, DateTimeKind.Local).AddTicks(6867),
                            Title = "Work"
                        },
                        new
                        {
                            Id = 3,
                            Color = "00FFFF",
                            Date = new DateTime(2024, 7, 15, 22, 19, 6, 962, DateTimeKind.Local).AddTicks(6869),
                            Title = "Start"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
